hop_aroma_list = [[1,'Admiral','orange','tea','fresh','sap'],
[2,'Agnus'],
[3,'Ahtanum','grapefruit','geranium'],
[4,'Amarillo','grapefruit','orange','lemon','melon','apricot','peach'],
[5,'Amarillo Gold'],
[6,'Apollo'],
[7,'Aquila'],
[8,'Aramis','green','herbal','spicy','citrus'],
[9,'Atlas'],
[10,'Atlas (Styrian Atlas)'],
[11,'Aurora','noble'],
[12,'Aurora (Super Styrian Aurora)'],
[13,'Azacca'],
[14,'Banner'],
[15,'Belma'],
[16,'Bitter Gold','pear','watermelon','stone fruit','fresh cut grass'],
[17,'Boadicea','floral','orchard blossom','ripe fruit'],
[18,'Bobek','noble'],
[19,'Bobek (Styrian Golding B)'],
[20,'Bramling Cross','blackcurrant','loganberry','vanilla'],
[21,'Bravo','orange','vanilla'],
[25,'Brooklyn','grapefruit','passionfruit','spice','sweet hay'],
[26,'Bullion','zesty','blackcurrant'],
[27,'Bullion'],
[28,'Calypso'],
[29,'Cascade','grapefruit','floral'],
[30,'Cascade'],
[31,'Cashmere','melon','lemon','lime','spice'],
[32,'Celeia','noble'],
[33,'Centennial','lemon','floral'],
[34,'Challenger','cedar','green tea','sweet fruit'],
[35,'Chelan','mild'],
[36,'Chinook','grapefruit','spicy','pine'],
[37,'Chinook'],
[38,'Citra','grapefruit','melon','lime','gooseberry','passion fruit'],
[39,'Cluster','floral','earthy','sweet fruit'],
[40,'Columbia','fuggle type'],
[41,'Columbus (Tomahawk)','black pepper','licorice','citrus'],
[23,'BrewerGold','blackcurrant','spicy'],
[24,'BrewerGold','blackcurrant','spicy'],
[42,'Columbus/Tomahawk/Zeus (CTZ)'],
[43,'Comet','wild american','grass','grapefruit'],
[44,'Crystal','woody','green'],
[45,'Delta'],
[46,'Dr. Rudi','resin','pine','lemongrass'],
[47,'East Kent Goldings (EKG)','lavendar','honey','lemon','thyme','orange','grapefruit'],
[48,'El Dorado'],
[49,'Ella (aka Stella)','floral','noble','spicy','star anise','grapefruit'],
[50,'Equinox (HBC 366)'],
[51,'Eroica','fruity'],
[52,'Eureka!'],
[55,'Feux Coeur Francais'],
[56,'First Gold','geranium','magnolia','apricot','tangerine','orange marmalade'],
[57,'Fuggle (UK)','green tea','mint','grass','floral'],
[58,'Fuggle'],
[59,'Fuggle'],
[121,'Palisade'],
[53,'Falconers Flight'],
[60,'Fuggle (US)','mild','wood','grass','mint'],
[62,'Galaxy','passionfruit','peach','clean citrus'],
[63,'Galena','sweet','pear','pineapple','lime','blackcurrant','grapefruit'],
[64,'German Tradition'],
[66,'Glacier','plum','blackberry','wood'],
[67,'Golding','delicate','sweet floral'],
[68,'Golding'],
[69,'Goldings'],
[71,'Green Bullet','spicy','dried fruit','floral'],
[72,'Greenburg'],
[73,'HBC 291 (Experimental)'],
[74,'HBC 342 (Experimental)'],
[75,'HBC 366 (Experimental)'],
[76,'Hallertau','noble'],
[77,'Hallertau Blanc','passion fruit','grapefruit','pineapple','grape','lemongrass'],
[78,'Hallertau Magnum'],
[122,'Pekko'],
[65,'Gesho Kitel'],
[70,'Goldings'],
[79,'Hallertau Taurus','blackcurrant','pepper','zesty'],
[80,'Hallertauer'],
[81,'Hallertauer Hersbrucker'],
[82,'Hallertauer Mittelfrueh','grass','tea','citrus'],
[83,'Hallertauer'],
[84,'Harmonie'],
[85,'Helga (Southern Hallertau)','pleasant','noble'],
[86,'Herald','orange','grapefruit'],
[87,'Herkules','robust','melon'],
[88,'Hersbrucker','hay','tobacco','orange'],
[89,'HopShot'],
[90,'Horizon','floral bouquet','spicy'],
[91,'Huell Melon','honeydew melon','orange','strawberry','tropical fruit'],
[92,'Idaho #7'],
[93,'Jarrylo'],
[94,'Kohatu','tropical fruit'],
[95,'Lemondrop'],
[96,'Liberty','noble','floral','herbal','spicy','delicate','lemon'],
[97,'Liberty'],
[98,'Lublin'],
[99,'Lublin (Lubelski)'],
[100,'Magnum','apple','pepper'],
[101,'Mandarina Bavaria','tangerine','grapefruit','lime'],
[102,'Marynka'],
[103,'Merkur (Hallertauer Merkur)'],
[104,'Millenium','resin','herbal','floral','pear'],
[105,'Mosaic (HBC 369)','blueberry','tangerine','papaya','blossoms','rose','bubble gum'],
[106,'Motueka','lemon','lime','tropical fruit'],
[107,'Mt. Hood','pungent'],
[108,'Mt. Rainier','noble','licorice','floral'],
[109,'Nelson Sauvin','white wine','gooseberry','grape','sauvignon blanc'],
[110,'Newport','wine','balsamic'],
[111,'Northdown','floral','pine','cedar','berry'],
[112,'Northern Brewer','mint','pine','grass'],
[113,'Nugget','green','wood','ginger'],
[114,'Olympic','citrus','spicy'],
[115,'Opal','sweet spice','pepper','clean citrus','anise'],
[116,'Orion','spicy'],
[117,'Pacific Gem','oak','blackberry'],
[118,'Pacific Hallertau (aka Pacifica)'],
[119,'Pacific Jade','fresh citrus','black pepper'],
[120,'Pacifica','orange zest','marmalade'],
[123,'Perle','mint','tea','pepper'],
[124,'Perle','spicy','floral'],
[125,'Phoenix','spicy','floral','chocolate'],
[126,'Pilgrim','lemon','grapefruit','pear','berry'],
[127,'Pilot','marmalade','lemon','spice'],
[128,'Pioneer','lemon','grapefruit','cedar','herbal'],
[129,'Polaris','mint','pineapple','menthol'],
[130,'Premiant','pleasant','mild'],
[131,'Pride of Ringwood','cedar','oak'],
[132,'Progress','grass','mint','sweet','honey','blackcurrant'],
[133,'Rakau (Alpharoma)','stone fruit','fig','apricot','resin','pine needle'],
[134,'Riwaka','grapefruit','citrus'],
[135,'Rubin'],
[136,'Saaz','earthy','spicy'],
[137,'Santiam','black pepper','spicy','floral'],
[138,'Saphir','spicy','floral'],
[139,'Satus'],
[140,'Select Spalt','spicy','grass'],
[141,'Simcoe','passion fruit','berry','pine','earth','citrus'],
[142,'Sladek','peach','grapefruit','passion fruit'],
[143,'Smaragd (Emerald)','anise','tobacco','clove'],
[144,'Sonnet Golding'],
[146,'Southern Cross','lemon peel','lime','tropical fruit','pine'],
[147,'Sovereign','floral','grass','herbal','mint','sweet','pear'],
[148,'Spalt Spalter','noble'],
[149,'Spalter'],
[150,'Spalter Select'],
[151,'Sterling','noble','herbal','spicy','floral'],
[152,'Sticklebract','citrus','pine'],
[153,'Strisslespalt','herbal','grass floral','spicy','grapefruit'],
[154,'Styrian Aurora (Super Styrian)'],
[155,'Styrian Bobek'],
[156,'Styrian Celeja'],
[157,'Styrian Golding (Savinja Golding)','noble'],
[158,'Styrian Goldings'],
[159,'Summer (Summer Saaz)','apricot','melon'],
[160,'Summit','pepper','incense','anise','orange','pink grapefruit','tangerine'],
[161,'Sun'],
[162,'Super Alpha'],
[163,'Super Galena'],
[164,'Super Pride','resin','fruit'],
[165,'Sussex','earthy','grass','mint','citrus','vanilla'],
[167,'Tahoma','lemon','grapefruit','cedar','pine','green melon','floral','pepper'],
[168,'Target','sage','pepper','citrus','marmalade','tangerine'],
[169,'Tettnang','spicy','pepper','black tea'],
[170,'Tettnang (Tettnang Tettnager)','noble'],
[171,'Tettnang'],
[172,'Tillicum'],
[173,'Tomahawk','pungent','black pepper','licorice','curry'],
[174,'Topaz','resin','grass','lychee'],
[175,'Tradition','grass','tea','lavendar','orange'],
[176,'Triple Pearl','melon','orange','resin','spice','pepper'],
[177,'Triskel','floral','herbal','citrus','spicy'],
[178,'Tsingtao Flower'],
[179,'Ultra','mild','floral','bouquet'],
[180,'Vanguard','wood'],
[181,'Vic Secret','pine','earth','pineapple','passionfruit'],
[182,'Victoria'],
[183,'Wai-iti','peach','apricot','spice','lime','tropical fruit'],
[184,'Waimea','citrus','pine','herbal'],
[185,'Wakatu (Hallertau Aroma)','lime zest','floral'],
[186,'Warrior','mild','resinous'],
[187,'Whitbread Golding Variety (WGV)','fresh earth','floral','sweet fruit'],
[188,'Willamette','floral','incense','elderberry'],
[189,'Willamette'],
[190,'Wye Challenger'],
[191,'Yakima Gold','grapefruit','lemon zest'],
[192,'Zeus','pungent','black pepper','licorice','curry'],
[193,'Zythos','pineapple','citrus','pine'],
[22,'Brewers Gold'],
[54,'Falconers Flight 7Cs Blend','lemon','grapefruit'],
[61,'Fuggles'],
[145,'Sorachi Ace','lemon','lime','dill'],
[166,'Sylva','floral','herbal','noble']]

hop_aroma_list.each do |hop_list|
  if hop_list.length > 2
    hop = Hop.find_by_id(hop_list[0])
    aromas = []
    hop_list[2..(hop_list.length-1)].each do |aroma|
      aromas.push(aroma)
    end
    hop.aromas=aromas.join(', ')
    hop.save!
  end
end
